### ISSUE TITLE
Include HttpClient name in log messages

### ISSUE THREAD

**Issue by andrewlock** [aspnet/HttpClientFactory#51]
I was just watching [the community standup](https://www.youtube.com/watch?v=Lb12ZtlyMPg&list=PL1rZQsJPBU2StolNg0aqvQswETPcYnNKL&index=0) (great demo BTW), and noticed one thing with the log messages - they don't include the `HttpClient` name in the source. 

e.g. For the `github` named client, the log sources are `System.Net.Http.github` and `System.Net.Http.github.ClientHandler`. 

That makes it a pain if I want to set a filter for the log messages from _all_ clients. (e.g. to `> Warning`). I would either need to setup log filtering for each individually named client, or blanket filtering across the whole `System.Net.Http` namespace. 

If you change [these lines](https://github.com/aspnet/HttpClientFactory/blob/9c031dde884b6f12b703da551919fe0cdc6b7869/src/Microsoft.Extensions.Http/Logging/LoggingHttpMessageHandlerBuilderFilter.cs#L39) to be

```c#
var outerLogger = _loggerFactory.CreateLogger($"System.Net.Http.HttpClient.{builder.Name}");
var innerLogger = _loggerFactory.CreateLogger($"System.Net.Http.HttpClient.{builder.Name}.ClientHandler");
```

(or similar), then we can filter on `System.Net.Http.HttpClient` and it will apply to all clients.

**Comment by glennc** [comment]
Thing we will talk about for this issue:

1.  Can we implement a wildcard in log filtering such that I can set System.Net.Http.HttpClient.*.Polly to Debug and get debug information for all Polly handlers but normal logging for all others. This is based on us having a consistent pattern for all the handlers and should make it easy for everyone to adhere to if they want to provide the same support.
2. We can add HttpClient to our source names, that seems fine.
3. Add a suffix onto the outer logger so that it can be filtered separately.
4. Add the client name to log messages.

**Comment by rynowak** [comment]
I'm going to close this issue as fixed. We addressed the feedback from @andrewlock already.

Two things I haven't done yet. 

Going to open an issue on Logging for the discussion about wildcards.

 I skipped `4. Add the client name to log messages.` because I don't remember the use case for it. The client name is now part of the log source names, so you always have it. If we think of an important need for this in the future we can just do it then, it's pretty simple to add.
