### ISSUE TITLE
Support libraries not just applications

### ISSUE THREAD

**Issue by normj** [aspnet/HttpClientFactory#55]
With this being all in one package that ties the HttpClient caching, the DI extension methods and targeting netcorestandard2.0 it makes it hard for class libraries to pull in just the IHttpClientFactory support. 

For example the [AWS SDK for .NET](https://github.com/aws/aws-sdk-net) which targets .NET Standard 1.3 would not be able to use this library. That is unfortunate because dealing with the HttpClient lifecycle issues is one of our biggest challenges. We don't want to add the other Microsoft.Extension packages dependencies to our SDK though.

Would it be possible to move the code for IHttpClientFactory and its implementation into a separate nuget package targeting .NET Standard 1.3 or less and move the DI extension methods into a separate package? That way IHttpClientFactory becomes useful for things besides ASP.NET Core applications.

**Comment by johnkors** [comment]
I wholeheartedly agree.

For me, I'd welcome this feature for legacy full framework apps, but none of the dependencies for this package make sense to bring in as part of it. We're using other containers and configuration mechanisms. A bare bones version like @normj mentions makes more sense to me.

**Comment by davidfowl** [comment]
Is th problem netstandard 2.0 or something else? There are no dependencies here that aren’t required.

Can you flesh out a proposal with what you expect the configuration and consumption of the minimal API would look like?

@johnkors this already works in full Framework applications.

**Comment by johnkors** [comment]
@davidfowl Sorry, I was not talking about Full Framework - but legacy .NET apps. Example: 

If I'm using ASP.NET MVC / Web API or any other app not using the new MS DI mechanisms (`ServiceCollection` and friends), I don't see why I'd care for [HttpClientFactoryServiceCollectionExtensions](https://github.com/aspnet/HttpClientFactory/blob/dev/src/Microsoft.Extensions.Http/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs). The DI bits of .NET Core are irrelevant there. We´re using any community IoC framework, like autofac/ninject/structuremap.

The same goes for the `Options` dependency. In an old-style app, reading config is more like to be done via the ConfigurationManager APIs, or any selfwritten abstraction on top if it. Not the new Option+Configuration-abstractions of .NET Core-apps. So why would I want to bring in a dependency for just for the sake of an unused extension method, [these helpers](https://github.com/aspnet/HttpClientFactory/blob/dev/src/Microsoft.Extensions.Http/DependencyInjection/HttpClientBuilderExtensions.cs#L35) ?

Same for logging. Most legacy apps use NLog/Serilog/Log4Net directly, and haven't been rewritten to fit with Microsofts logging abstractions.

So, for me, it makes more sense for this factory to be split into two NuGets
1) `HttpClientFactory` (no deps, the factory itself)
2) `HttpClientFactory.AspNetCore` (aspnet core abstractions deps, making it work with asp.net core conventions, ext methods)

So, moving the extension methods and dependencies relevant to AspNetCore conventions into 2) instead of 1).

Then in old style apps, I can use 1) without bringing along unwanted deps, and where I use aspnet core, I can use 2) where I'm knowingly following those conventions anyways.

Does it make sense?

**Comment by davidfowl** [comment]
Not really. I’d like to see something more concrete. Options is only loosely related to configuration. The reason we try to avoid designing components to work both with and without a DI container is because it’s extremly hard to get right. When you can’t rely on any cross cutting concerns being available you end up making abstractions for everything and it’s the worst of all worlds. 

What exactly do you want to get out of the client factory and how do you expect to comsume it in “legacy” applications. 

I’d like to see the alternate API proposal for configuring it and how you expect to register it in your custom DI container (or not).

Noting here is ASP.NET Core specific, Extensions libraries usually depend on other extension libraries and that’s the case here.

**Comment by johnkors** [comment]
Yeah, I get that it´s not _ASP.NET Core_ specific - but it's still tied to newer abstraction APIs mostly used in the ASP.NET Core / .NET Core sphere - and hence in practice, I can´t see this NuGet being used in legacy apps at all unfortunately. And that´s a pity, since it´s really something we´d like in older apps as well. But if, that´s how it is, it´s how it is. We´ll just have to wait for a migration some year down the line.

I don´t have an alternate idea/proposal how to untangle this from the newer abstractions or if it is doable at all, sorry. By the looks of it, at least remove service locators, and inject deps in ctors instead. Not sure why it´s done that way, but you probably have your reasons :)

**Comment by normj** [comment]
I'll try and take a crack at putting something together more concretely. The netstandard2.0 is a deal breaker as we need our library to support .NET Core 1.0 users as well as .NET Core 2.0. Maintaining 2 separate lines is not feasible with our release cadence and size of the SDK.

Ultimately what I would like to reuse from this package is just the basic caching logic, handling the DNS refresh and properly disposing clients with the weak references. As a library we don't expect consumers to configure the HttpClients as that is abstracted away to handle the differences between .NET Framework, HttpWebRequest, and .NET Core, HttpClient. If I had this HttpClientFactory available to me the Core component would directly instantiate the DefaultHttpClientFactory, or something like that, and fetch the HttpClients from that instead of our home grown solution.


On a side note, it looks like only one set of handlers is cached per named client. We ran into scalability issues with that on Linux and had to create a pool of HttpClients when running on Linux. From our investigation sending every request through one HttpClient would max out the underlying libcurl resources. This is the GitHub issue if you are curious https://github.com/aws/aws-sdk-net/issues/703

**Comment by glennc** [comment]
Here is what I currently think about this discussion. I am always open to being convinced otherwise of course :).

1. There is a general problem of managing HttpClient in .NET. In full framework this is taken care of with a combination of service point manager and caching a single HTTPClient. Nothing we have done in the factory so far is superior to the results you can get with Service Point Manager on full framework AFAIK. On Core we don't have that but are going to have a managed handler that doesn't suffer from the potential pitfalls of the winhttp and libcurl based handlers we have today. This should be the answer to the people wanting to avoid all the DI and app model specific dependencies that the factory comes with. The factory is about codifying the outgoing middleware pipeline, allowing easy to configure named clients, and using DI magic for typed clients. Handling the lifetime of HttpClient is nice, but will not be required once the managed handler is the default in .NET Core and I fully intend to remove as much of that aspect of the factory as I can when the time comes. So by re-factoring this and having everyone depend on the factory we are inventing a bunch of work that we could just defer until the managed handler is available. We can have a discussion about whether or not the managed handler will work in all the places you want your library to run, but that should happen in the corefx repo with the people that work on it. In short, make sure the managed handler isn't going to solve all the problems you have before we jump onto generalizing a higher level abstraction that was designed with apps as a primary consumer.

2. Some people want to use the factory in apps that are not ASP.NET Core. For these people I am hoping that the `GenericHostBuilder` provides a way to new up just enough of the DI system and other primitive concepts to use things like the factory without actually creating a webhost or otherwise tying you to web stuff. It does tie you to the DI pattern and app lifetime management, but nothing web/aspnet core specific. I haven't fully fleshed this idea out, the main pain point I envision is that you would have to tie things like ILogger to whatever logging system you are using in your other app, this should be possible but might not be super nice. Maybe if you are using some sort of DI setup already it will not be too bad though. I started playing with stuff like this here: https://github.com/glennc/httpclientfactorysample/blob/48e006f44e6c9312e025ea1944648906c393dc46/src/WebUI.WebForms/Global.asax.cs

3. For the scalability issues of having a single pipeline, we have some data from testing we did around this earlier but I haven't yet talked to enough people to know exactly what we intend to do. The last test result I saw showed there was a hard limit with a single cache and that the most effective mitigation was to pool several and allocate requests to the shortest queue. This helped mitigate the problems you get when mixing long-running and short requests on a single client that something like round-robin or random would have. I still need to catch up on where we stand now as this testing was before 2.0 and I think at least some improvements were made in the 2.0 time-frame.

**Comment by normj** [comment]
After digging through the code I see now that most of the code is about middleware and configuration and not as much on the caching logic. Watching Ryan Nowak from the ASP.NET community standup I got most excited about the caching part and was hoping to reuse it. It would be great if those concerns were separated but I can understand if that is beyond the scope of what is being accomplished with this package. I might need to graph some of the caching logic into our home brew solution to better handle  DNS updates.

Sounds like what I really need to look into is the upcoming managed handler. Is there any docs on that or should I just dive into to the corefx repo?

The GenericHostBuilder sounds interesting because it is kind of an awkward to explain Configuration and in our case AWS service clients from DI without the context of an ASP.NET Core application. Having a more unified story for that across the different types of applications would help getting .NET Framework developers more accustomed to .NET Core. Is that part of .NET Core 2.1?

In our caching we ended up defaulting our pool size to the number of cores just to have some sort of reasonable default and then let the developer adjust the pool size if they need to.

I'm fine closing this issue if you want keep the caching and middleware logic together for now. I would recommend seeing if you really need to have it be .NET Standard 2.0 cutting off libraries that want/need to support both .NET Core 1.0 and 2.0.

**Comment by glennc** [comment]
Closing this issue as our discussion is done for the most part.

@normj Looks like the managed handler will be coming sooner than I thought when I first responded to this issue. You should go look in the corefx repo for issues and such related to it. All the code is there and being worked on right now.

**Comment by normj** [comment]
@glennc Thanks, excited to start testing the new managed handler.

**Comment by tmenier** [comment]
@glennc 

> Nothing we have done in the factory so far is superior to the results you can get with Service Point Manager on full framework AFAIK.

Out of curiosity, is that in reference to the `ConnectionLeaseTimeout` setting? If so, I really think the record needs to be set straight on what that setting actually does, because based on a couple popular blog posts, there's a widespread belief that it's some sort of low-level black-magic silver bullet and that if you're on a platform that doesn't support it, you're out of luck. In fact, all that setting does (as I first saw [mentioned](https://github.com/dotnet/corefx/issues/11224#issuecomment-243189533) by Darrel Miller and confirmed from the source code) is send a `Connection:Close` request header at regular intervals. That is very easy to replicate, such as in a custom handler. (It's also far from a perfect solution, but there is no perfect client-side solution to this problem.)

Please do set me straight if there's more to what `ServicePointManager` is doing to address the DSN problem specifically, but I don't believe there is. The corefx team might be better able to answer, but I just wanted to clarify that, to the best of my knowledge, `ServicePointManager` provides nothing in terms of a superior solution that can't be easily replicated on any platform.

**Comment by tmenier** [comment]
@karelz Thank you for chiming in. The source code you linked to is what I spent some time investigating a while back. My goal was to determine what actually _happens_ when this timeout period expires. I expected I'd come across a socket being explicitly closed or something similar, but all I found was [this line](https://referencesource.microsoft.com/#System/net/System/Net/_Connection.cs,632), which just sets `KeepAlive` to false on the next request associated with that `ServicePoint`, and all that effectively does is send the `Connection:Close` header.

Maybe I'm still missing something, but my assumption is that if you're using an `HttpClient` per host being called, and you send a `Connection:Close` header on the next request to that host after some timer interval, you'd pretty much have something equally effective.

**Comment by karelz** [comment]
> if you're using an `HttpClient` per host being called, and you send a `Connection:Close` header on the next request to that host after some timer interval, you'd pretty much have something equally effective.

That will work, if the underlying pool has only 1 connection opened to the server. What if there are multiple?

**Comment by tmenier** [comment]
Ah, ok, that makes sense.  So even if you were to dispose HttpClient and create a new one at regular intervals, there's still no guarantee that you're not still using underlying connections that were never closed, correct?

**Comment by krema** [comment]
There is a dirty workaround for that. To use it in non core apps you can reference Microsoft.AspNetCore  and create with its help an instance of it which you can use anywhere. 

      var service = new ServiceCollection();
      service.AddHttpClient();

      var provider = service.BuildServiceProvider();
      var httpClientFactory = provider.GetService<IHttpClientFactory>();

**Comment by davidfowl** [comment]
What features do you need from the factory?

**Comment by tmenier** [comment]
@valeriob Hopefully someone will correct me if this is wrong but I believe the features you're looking for will be available automatically to anyone using your library who is targeting .NET Core 2.1, because the real magic is happening down in [SocketsHttpHandler](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-2-1#sockets-improvements), which `HttpClient` uses by default in Core 2.1.

**Comment by martincostello** [comment]
The performance changes are in the framework, but not the handler rotation - that's handled by the factory.

**Comment by tmenier** [comment]
@martincostello Doesn't [SocketsHttpHandler.PooledConnectionLifetime](https://github.com/dotnet/corefx/issues/11224#issuecomment-394396643) effectively solve the same [problem](http://byterot.blogspot.com/2016/07/singleton-httpclient-dns.html) that handler rotation solves?

**Comment by davidfowl** [comment]
@tmenier  That's correct.

**Comment by martincostello** [comment]
I was under the impression that the new handler didn't solve _everything_ and that the factory was needed for 2.1 to do some things that didn't make their way fully into the 2.1 release for all use cases.

**Comment by tmenier** [comment]
I think it's understandable that there's confusion in the community about which of these bits run where, largely based on:

1. Virtually everything written about `HttpClientFactory` seems to intimately tie it to ASP.NET Core 2.1, when in fact it lives in [Microsoft.Extensions.Http](https://www.nuget.org/packages/Microsoft.Extensions.Http/), which targets .NET Standard 2.0. (The official [docs](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests) say "available since .NET Core 2.1", which, while technically true, is itself a little misleading.)

2. The common misconception (based on names/versions/release dates) that ASP.NET Core 2.1 is "ASP.NET for .NET Core 2.1", when in fact they're totally independent; the former gladly runs on other platforms/versions.

The continuing innovations with both HttpClientFactory and ASP.NET Core are great for the community, I just think it's a little unfortunate that the branding/communications are causing people to believe they're less "available" than they actually are.

**Comment by rynowak** [comment]
> Am I doing something wrong wanting to write my business logic in a netstandard library without adding 20 (20 !!) nuget packages to do an http request ?

If that's the issue then I'd suggest letting callers pass in an `HttpClient` instance to your library. We intentionally designed the factory so that libraries and other utilities don't need to couple themselves to it. It's as easy as providing a constructor that accepts `HttpClient`. 

Our experience building the factory is that users have vastly different requires for configuring auth/proxy/transport related settings for HttpClient - if you're trying to abstract over HttpClient totally in your library then *somebody* is going to have a problem using it due to their configuration.

> I'm just saying that the factory solves an important problem in a good tested way, pls decouple it from Microsoft.Extensions.DependencyInjection, Microsoft.Extensions.Logging and Microsoft.Extensions.Options !

If you're primarily interested in the lifetime management, then that's feedback for dotnet/corefx. That's one feature that we provide and there are a number of ways to solve that problem. 

The major feature set that we provide is the configuration experience and "on by default" diagnostics. I would state that the major value we provide **is** Options/DI/Logging.
