### ISSUE TITLE
Consider using ActivatorUtilities.CreateFactory in DefaultTypedHttpClientFactory

### ISSUE THREAD

**Issue by pakrym** [aspnet/HttpClientFactory#76]
`ActivatorUtilities.CreateInstance` is 30x slower than invoking factory delegate.

**Comment by rynowak** [comment]
Does ActivatorUtilities do any caching? What's likely to happen at this point is that we'd have to implement our own concurrent-dictionary-backed cache for this.

I don't really want to redesign the API https://github.com/aspnet/HttpClientFactory/blob/8bcec63906b60a97768df2dbbfe7ebb3275c10ed/src/Microsoft.Extensions.Http/DefaultTypedHttpClientFactory.cs since I think there's some value in keeping it simple.

**Comment by pakrym** [comment]
No, unfortunately, it doesn't.

I know you said that you don't want to redesign the API but will ask anyway :). Why not make it `ITypedHttpClientFactory<T>`, then you can cache delegate inside and allow DI to do the lookup which it already has to do.

An additional benefit is that it allows customers to replace factories on per client type basis.

**Comment by rynowak** [comment]
64e9d90
